# Generated by Django 3.1.4 on 2021-01-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Naver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('roadAddress', models.CharField(max_length=200)),
                ('mapx', models.IntegerField()),
                ('mapy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('weather_summary', models.TextField()),
                ('now_temp', models.TextField()),
                ('dust', models.TextField()),
                ('little_dust', models.TextField()),
            ],
        ),
    ]
