# Generated by Django 3.1.4 on 2021-01-09 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='like_users',
            field=models.ManyToManyField(default=False, related_name='like_community', to=settings.AUTH_USER_MODEL),
        ),
    ]
